apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app-prod

resources:
- ../../base
- pdb.yaml

# ↓↓↓ 這一段由 App Repo 的 CI (`kustomize edit set image`) 自動改寫，人工不要手改 ↓↓↓
images:
- name: ghcr.io/graylee0128/devops-app
  newName: ghcr.io/graylee0128/devops-app
  newTag: 64b022be260d5fbc8032f07a9792c6162e795734
# ↑↑↑ CI 寫入點 ↑↑↑

replicas:
- count: 3
  name: devops-app

patches:
- path: patch-ingress.yaml
- path: patch-antiaffinity.yaml
